name: mini_project_01
channels:
  - conda-forge
  - defaults
  - zimmf
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit  # [not (osx and arm64)]
  - matplotlib
  - seaborn
  - pyyaml
  - ruff
  - tqdm
  - python-dotenv