defaults:
  - _self_
  - training: training_config_flow
  - optimizer: adam
  - models: flow
  - priors: mog


flow:
  - _self_
  - training: training_config_flow
  - optimizer: adam
  - models: flow
  - priors: mog

vae_vamp:
  - _self_
  - training: training_config
  - optimizer: adam
  - models: vae
  - priors: vamp

latent_dim: 10
T: 1000
num_transformations_flow: 10
num_hidden_flow: 2048
